name: Build
on:
  push:
    branches:
      - main # or the name of your main branch

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarQube scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarQube scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"tamilselvansellamuthu_mywebsite" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
          dotnet build 'mywebsite.sln'
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          
     #Add msbuild to PATH
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
  
     #To build dotnet application using MSBuild
      - name: Build
        run: msbuild ./mywebsite.sln
        
     #To Packackage dotnet Application
      - name: Package
        run: |
          dotnet pack .\mywebsite --configuration Release
          
    #To Add nuget artifacts repository as source to push artifacts.
      - name: AddSource
        run: dotnet nuget add source ${{ secrets.NEXUS_URL }} --name "nexus" --username  ${{ secrets.NEXUS_USER_NAME }} --password ${{ secrets.NEXUS_PASSWORD }}

    #To Push nuget package to artifacts repository using GitHub Secrets.
      #- name: Push
      #  run: |
      #    dotnet nuget push "src\ApplicationCore\bin\Release\ApplicationCore.1.0.0.nupkg"  --api-key ${{ secrets.NEXUS_API_KEY }} --source "nexus"
      
    #To Publish dotnet application
      - name: Publish
        run: dotnet publish --configuration release
        
    #To Compress the Application.
      - name: Compress
        run: Compress-Archive D:\a\mywebsite\mywebsite\mywebsite\bin\Release\netcoreapp3.1\publish\ D:\a\mywebsite\mywebsite\mywebsite\bin\Release\netcoreapp3.1\publish\mywebsite.zip
        
        
    #To Compress the Application.
      - name: Compress2
        run: |
          $ArtifactName = "mywebsite"
          $NexusArtifactName = "$ArtifactName-timestamp.zip"
          Compress-Archive D:\a\mywebsite\mywebsite\mywebsite\bin\Release\netcoreapp3.1\publish\ .\$NexusArtifactName
          echo $NexusArtifactName
          pwd
#                  $timestamp = Get-Date -Format "yyyy-MM-dd-HH:mm:ss"
#          $NexusArtifactName = "$ArtifactName-$timestamp.zip"
        
    #To Set PSCredentials.
      - name: PSCredentials
        run: |
          $NexusPassword = ConvertTo-SecureString "admin" -AsPlainText -Force
          $NexusCred = New-Object System.Management.Automation.PSCredential ( "admin" , $NexusPassword)
          Invoke-WebRequest -uri http://34.132.65.36:8081/repository/raw_repo/mywebsite.zip -Method Put -Infile D:\a\mywebsite\mywebsite\mywebsite\bin\Release\netcoreapp3.1\publish\mywebsite.zip -ContentType 'application/zip' -Credential $NexusCred -AllowUnencryptedAuthentication
          
    #To Push Compressed Application to Nexus Repo.
      #- name: PushToNexus
      #  run: Invoke-WebRequest -uri http://34.132.65.36:8081/repository/raw_repo/mywebsite.zip -Method Put -Infile D:\a\mywebsite\mywebsite\mywebsite\bin\Release\netcoreapp3.1\publish\mywebsite.zip -ContentType 'application/zip' -Credential $NexusCred
        
