#Name of the workflow.
name: Sample dot net workflow

#Workflow starts when below events occurs. Ex. code pushed to main branch or pull_request raised to main branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#Set of Job(s) runs for the event. Ex. build is a job.
jobs:
  build:

#Environment(s) used to run. Ex.ubuntu, mac-os, windows.
    runs-on: [windows-latest]

#Set of step(s) for the job(ex. build)
    steps:
    
    #Checkout the code. uses opensource action (https://github.com/actions/checkout)
    - uses: actions/checkout@v2
    
    #To Set up dotnet 5.0 environment using opensource action (https://github.com/actions/setup-dotnet)
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    #To build dotnet application using MSBuild
    - name: Build
      run: dotnet build "mywebsite.sln"
